
find_path(SDL2_image_INCLUDE_DIR SDL_image.h
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES include/SDL2 include
)

find_library(SDL2_image_LIBRARY
	NAMES SDL2_image
	HINTS
	$ENV{SDL2DIR}
	PATH_SUFFIXES x64 x86
)

unset(_SDL2_IMAGE_ARCH_DIR)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_image REQUIRED_VARS SDL2_image_LIBRARY SDL2_image_INCLUDE_DIR)
